name: RailSwitcher
main: haveric.railSwitcher.RailSwitcher
version: 1.0.2
author: haveric
dev-url: http://dev.bukkit.org/server-mods/railswitcher/
softdepend: [WorldGuard]
description: >
             Switch placed rails with other types or directions
commands:
  railswitcher:
    description: Switch placed rails with other types or directions
    usage:
    
permissions:
    railswitcher.*:
        description: Gives access to all RailSwitcher Commands
        children:
            railswitcher.switch: true
    railswitcher.switch:
        description: Allows switching of rails with other types and rotating rails.
        default: false