name: RailSwitcher
main: haveric.railSwitcher.RailSwitcher
version: 1.0.6
author: haveric
dev-url: http://dev.bukkit.org/server-mods/railswitcher/
softdepend: [WorldGuard, Towny, CoreProtect, LogBlock]
description: >
             Switch placed rails with other types or directions
commands:
  railswitcher:
    aliases: [rs]
    description: Switch placed rails with other types or directions
    usage:
    
permissions:
    railswitcher.*:
        description: Gives access to all RailSwitcher Commands
        children:
            railswitcher.switch: true
            railswitcher.admin: true
    railswitcher.switch:
        description: Allows switching of rail types and rotating rails.
        default: false
    railswitcher.admin:
        description: Allows use of admin commands.